### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by kasperrt** [micantoine/svelte-preprocess-cssmodules#18]
When using svelte with typescript, the builds always fails

```
ERROR in ./src/client/customer-journey/frontend/svelte/components/countdown/entry.svelte
Module build failed (from ../../node_modules/svelte-loader/index.js):
ParseError: Unexpected token
    at error (/Users/kary02/aller/wolverine-frontend/node_modules/svelte/compiler.js:16752:20)
    at Parser$1.error (/Users/kary02/aller/wolverine-frontend/node_modules/svelte/compiler.js:16828:10)
    at Parser$1.acorn_error (/Users/kary02/aller/wolverine-frontend/node_modules/svelte/compiler.js:16822:15)
    at Object.read_script [as read] (/Users/kary02/aller/wolverine-frontend/node_modules/svelte/compiler.js:7501:17)
    at tag (/Users/kary02/aller/wolverine-frontend/node_modules/svelte/compiler.js:15887:34)
    at new Parser$1 (/Users/kary02/aller/wolverine-frontend/node_modules/svelte/compiler.js:16787:22)
    at Object.parse$3 [as parse] (/Users/kary02/aller/wolverine-frontend/node_modules/svelte/compiler.js:16919:21)
    at /Users/kary02/aller/wolverine-frontend/node_modules/svelte-preprocess-cssmodules/dist/index.js:28:28
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kary02/aller/wolverine-frontend/node_modules/svelte-preprocess-cssmodules/dist/index.js:5:58)
 @ ./src/client/customer-journey/frontend/svelte/entrypoints/countdown/entry.ts 1:0-64 6:28-37
```

When removing any type-declaration from said file, compilation works again

**Comment by micantoine** [comment]
The problem is coming from the combination of multiple preprocessors using the svelte parser and walker and the way svelte runs its preprocessor in two phases. [Read more here](https://github.com/firefish5000/svelte-as-markup-preprocessor#motivation).

As a solution you should install the `asMarkupPreprocessor` package `npm install svelte-as-markup-preprocessor --save-dev` and do the following:

```js
// import packages
const { typescript } = require('svelte-preprocess');
const { asMarkupPreprocessor } = require('svelte-as-markup-preprocessor');
const cssModules = require('svelte-preprocess-cssmodules');

...

// svelte config
  preprocess: [
    asMarkupPreprocessor([
      typescript()
    ]),
    cssModules()
  ],
...
```
